### ISSUE TITLE
VisualConnectivity.cpp

### ISSUE THREAD

**Issue by SeyedAlirezaMalih** [SMoG-Chalmers/PST#10]
Hello, I'm trying to implement the PST with pstalgo, but got some errors and I guess its due to the files which are not in repos

###########
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C1083	Cannot open source file: '..\src\analyses\VisualConnectivity.cpp': No such file or directory	pstalgo	G:\src\analyses\VisualConnectivity.cpp	1	
############
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2039	'runtime_error': is not a member of 'std'	pstalgo	G:\Smart cities\13.Internships\Git\pstalgo\src\geometry\RegionPoints.cpp	39		
############
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C3861	'runtime_error': identifier not found	pstalgo	G:\Smart cities\13.Internships\Git\pstalgo\src\geometry\RegionPoints.cpp	39		
############
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2039	'runtime_error': is not a member of 'std'	pstalgo	G:\Smart cities\13.Internships\Git\pstalgo\src\geometry\RegionPoints.cpp	63		
############
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C3861	'runtime_error': identifier not found	pstalgo	G:\Smart cities\13.Internships\Git\pstalgo\src\geometry\RegionPoints.cpp	63

**Comment by martin-fitger** [comment]
VisualConnectivity.cpp was an experimental file and a reference to it was added to the repo by mistake. The reference has now been removed. Thanks for reporting this issue.
