### ISSUE TITLE
Values in the Attraction Reach Analysis

### ISSUE THREAD

**Issue by rtsaboya** [SMoG-Chalmers/PST#6]
Hi!
I am obtaining weird numerical results in the Attraction Reach analysis. The picture shows that the colors in the map make perfect sense, but the values are off. The minimal value is 125, even for segments that are obviously out of the 1600m radius defined for the analysis.

<img width="1154" alt="qgis-ltr-bin_JI61cQXXzP" src="https://github.com/SMoG-Chalmers/PST/assets/1327871/e53d9d81-6f1b-4313-926c-8825a14c6a58">

Both the network and the attractions (schools) are on the same (projected) CRS (EPSG 31982).

I also tried assigning weights equal to 1 to the schools, to see if anything changes, but the results remained the same.

I made a small video showing the steps I took to carry out the analysis: https://youtu.be/FbHvsyJNu1Q

Thanks in advance for any help!

**Comment by giannastavroulaki** [comment]
Dear Renato,
thanks for sharing this. It is indeed weird. All the steps you took are correct, so my guess is that something is going on with the datasets, probably the point dataset of schools. 

I recommend to download the latest PST version 3.2.5, and test again. This version works with shapefiles as well. 
And, just in case, recheck that the two datasets have the same projected coordinate system in the Layer Information panel. The coordinate systems are the sources of the weirdest of errors in PST. 

If you get the same errors with the latest version, I would have to check your datasets (network and schools) to understand what is going on. If you don't have a problem sharing, I am happy to have a look. 

Gianna

**Comment by rtsaboya** [comment]
Dear Gianna, thank you so much for your response.
I had not realized that I had to manually update the plugin, so I was using a previous version. I updated it but the problem persisted.

However, I was now able to get an error message warning that there were null geometries in the attractions layer. I deleted them and now everything works fine.

If anyone runs into the same problem, [this is how you can select null geometries ](https://gis.stackexchange.com/questions/74243/selecting-features-with-null-geometry-from-shapefiles-using-qgis)in order to delete them.

One important thing, though, is that the error appeared only in the shapefile version of the layer. When using the geopackage, it ran as before and gave the same wrong values.

Thanks again!
Congrats for this awesome tool!
Best,
Renato.
