### ISSUE TITLE
Error in angular betweenness: PSTAFastSegmentBetweenness()

### ISSUE THREAD

**Issue by rtsaboya** [SMoG-Chalmers/PST#8]
Hello!
I'm running into a 'PSTAFastSegmentBetweenness()" error when trying to run an angular betweenness analysis:

<img width="180" alt="qgis-ltr-bin_rKNNsZOw0w" src="https://github.com/SMoG-Chalmers/PST/assets/1327871/f0cdb279-2441-44c7-bfc4-846930851c46">

There is no further information, so I'm struggling to find a solution. 

I already:

1. Checked for null geometries;
2. Made sure the layer only has single parts features.
3. Checked the geometry validity (QGIS Toolbox > Vector Geometries > Check validity).

Angular integration analyses (global and local) worked just fine.

The file can be accessed here if someone would like to give it a try: [Geopackage (Dropbox link)](https://www.dropbox.com/scl/fi/3ygr65q5f4cofyzselupz/Mato-Grosso-do-Sul-mapas-de-segmentos.gpkg?rlkey=c0nc7qfndtuoniaqwy8p0kgqz&dl=0).

Thanks in advance for any help.

**Comment by giannastavroulaki** [comment]
Dear Renato, 
just click ok and it will continue with the calculations. Better yet, download the latest PST version 3.2.5 

Please let me know if the issue is fixed  

Best wishes,
Gianna

**Comment by rtsaboya** [comment]
Dear Gianna:
Thanks for your prompt reply. Yes, that solved the problem.
However, the results are weird / incorrect. I will try to figure out what is happening and, if not successful, open another issue, ok?
Thanks again.
Best regards,
Renato.

**Comment by giannastavroulaki** [comment]
Please check the analysis settings. This message appears when for example both the ‘no weight’ and ‘weight-by-length’ option are selected.
I suggest that you install the latest version where this message doesn’t appear

Best wishes
Gianna
________________________________
